### ISSUE TITLE
yadage: fail to pull workflow from GitHub

### ISSUE THREAD

**Issue by diegodelemos** [reanahub/reana-workflow-engine-yadage#21]
When submitting the following workflow:
```yaml
stages:
  - name: helloworld
    dependencies: [init]
    scheduler:
      scheduler_type: 'singlestep-stage'
      parameters:
        name: {stages: init, output: name, unwrap: True}
        outputfile: '{workdir}/greetings.txt'
      step:
        process:
          process_type: 'string-interpolated-cmd'
          cmd: 'python helloworld.py {name} {outputfile}'
        publisher:
          publisher_type: 'frompar-pub'
          outputmap:
            output: outputfile
        environment:
          environment_type: 'docker-encapsulated'
          image: 'reanahub/reana-demo-helloworld'
```
Using:
```console
$ curl -H "Content-Type: application/json" -X POST \
           -d '{"experiment":"atlas", \
                "toplevel":"github:diegodelemos/reana-demo-helloworld@2-add-helloworld-workflow", \
                "workflow": "hello.yaml", "nparallel": "100", "preset_pars": {}}' \
           http://192.168.99.100:31047/yadage
```
The following exception is raised:
```console
[2017-04-11 15:46:59,204: INFO/Worker-2] running recast workflow on context: {u'toplevel': u'github:diegodelemos/reana-demo-helloworld@2-add-helloworld-workflow', u'preset_pars': {}, u'experiment': u'atlas', u'nparallel': u'100', u'workflow': u'hello.yaml'}
[2017-04-11 15:46:59,204: INFO/Worker-2] running yadage workflow hello.yaml
[2017-04-11 15:46:59,209: ERROR/Worker-2] loading error: cannot find URI file:///code/github:diegodelemos/reana-demo-helloworld@2-add-helloworld-workflow//hello.yaml
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/yadageschemas/__init__.py", line 87, in yamlloader

  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1353, in file_open
    return self.open_local_file(req)
  File "/usr/lib64/python2.7/urllib2.py", line 1393, in open_local_file
    raise URLError(msg)
URLError: <urlopen error [Errno 2] No such file or directory: '/code/github:diegodelemos/reana-demo-helloworld@2-add-helloworld-workflow//hello.yaml'>
[2017-04-11 15:46:59,223: ERROR/MainProcess] Task tasks.run_yadage_workflow[f8d99bd6-f80a-4af6-97fb-3a638109ce2d] raised unexpected: RuntimeError()
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/reana_workflow_engine_yadage/tasks.py", line 76, in run_yadage_workflow
    run_yadage_workflow_standalone(str(jobguid), ctx)
  File "/code/reana_workflow_engine_yadage/tasks.py", line 63, in run_yadage_workflow_standalone
    backend=cap_backend) as ys:
  File "/usr/lib64/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/lib/python2.7/site-packages/yadage/steering_api.py", line 48, in steering_ctx
    ys.init_workflow(workflow, loadtoplevel, initdata, validate = validate, schemadir = schemadir)
  File "/usr/lib/python2.7/site-packages/yadage/steering_object.py", line 44, in init_workflow
    validate=validate
  File "/usr/lib/python2.7/site-packages/yadage/workflow_loader.py", line 5, in workflow
    data = yadageschemas.load(source, toplevel, schema_name, schemadir, validate)
  File "/usr/lib/python2.7/site-packages/yadageschemas/__init__.py", line 119, in load
    elif toplevel.startswith('http'):
  File "/usr/lib/python2.7/site-packages/yadageschemas/__init__.py", line 96, in load
    repo = repo,
  File "/usr/lib/python2.7/site-packages/jsonref.py", line 375, in load_uri
    loader(uri),
  File "/usr/lib/python2.7/site-packages/yadageschemas/__init__.py", line 91, in yamlloader
    else:
RuntimeError
```
Even though workflow spec validates correctly:
```console
[root@yadage-atlas-worker-2909073811-k9rtm code]# yadage-validate hello.yaml github:diegodelemos/reana-demo-helloworld@2-add-helloworld-workflow
workflow validates against schema
```

**Comment by diegodelemos** [comment]
Trying updating `yadage-schemas` and rebuilding the image to get last `yadage-schemas` last version.

**Comment by diegodelemos** [comment]
With:
```console
[root@yadage-atlas-worker-2909073811-zl5pd code]# pip freeze | grep schemas
yadage-schemas==0.6.0
```
Still some errors occur @lukasheinrich :
```console
[2017-04-11 17:49:38,525: INFO/MainProcess] Received task: tasks.run_yadage_workflow[81f6200b-8604-45c7-ae8a-5558e191fbc3]
[2017-04-11 17:49:38,527: INFO/Worker-1] getting socket..
[2017-04-11 17:49:38,528: INFO/Worker-1] running recast workflow on context: {u'toplevel': u'github:diegodelemos/reana-demo-helloworld@2-add-helloworld-workflow', u'preset_pars': {}, u'experiment': u'atlas', u'nparallel': u'100', u'workflow': u'hello.yam
l'}
[2017-04-11 17:49:38,824: INFO/Worker-1] no initialization data
[2017-04-11 17:49:38,825: INFO/Worker-1] added zmq tracker.. ready to go..
[2017-04-11 17:49:38,825: INFO/Worker-1] zmq publishing under: 81f6200b-8604-45c7-ae8a-5558e191fbc3
[2017-04-11 17:49:38,825: INFO/Worker-1] running yadage workflow hello.yaml on backend <yadage.backends.packtivitybackend.PacktivityBackend object at 0x3443190>
[2017-04-11 17:49:38,826: INFO/Worker-1] preparing adage coroutine.
[2017-04-11 17:49:38,826: INFO/Worker-1] starting state loop.
[2017-04-11 17:49:38,880: INFO/Worker-1] no nodes can be run anymore and no rules are applicable
[2017-04-11 17:49:38,880: INFO/Worker-1] exiting main polling coroutine
[2017-04-11 17:49:38,881: INFO/Worker-1] unsubmittable: 0 | submitted: 0 | successful: 0 | failed: 0 | total: 0 | open rules: 1| applied rules: 0
[2017-04-11 17:49:38,897: ERROR/MainProcess] Task tasks.run_yadage_workflow[81f6200b-8604-45c7-ae8a-5558e191fbc3] raised unexpected: ValueError('min() arg is an empty sequence',)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/code/reana_workflow_engine_yadage/tasks.py", line 76, in run_yadage_workflow
    run_yadage_workflow_standalone(str(jobguid), ctx)
  File "/code/reana_workflow_engine_yadage/tasks.py", line 68, in run_yadage_workflow_standalone
    log.info('zmq publishing under: %s', jobguid)
  File "/usr/lib64/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/lib/python2.7/site-packages/yadage/steering_api.py", line 76, in steering_ctx
    ys.run_adage(backend)
  File "/usr/lib/python2.7/site-packages/yadage/steering_object.py", line 71, in run_adage
    adage.rundag(controller = self.controller, **self.adage_kwargs)
  File "/usr/lib/python2.7/site-packages/adage/__init__.py", line 134, in rundag
    run_polling_workflow(controller, coroutine, update_interval, trackerlist, maxsteps)
  File "/usr/lib/python2.7/site-packages/adage/__init__.py", line 59, in run_polling_workflow
    trackprogress(trackerlist, controller.adageobj, method = 'finalize')
  File "/usr/lib/python2.7/site-packages/adage/__init__.py", line 28, in trackprogress
    map(lambda t: getattr(t,method)(adageobj), trackerlist)
  File "/usr/lib/python2.7/site-packages/adage/__init__.py", line 28, in <lambda>
    map(lambda t: getattr(t,method)(adageobj), trackerlist)
  File "/usr/lib/python2.7/site-packages/adage/trackers.py", line 46, in finalize
    viz.print_dag(adageobj.dag,'dag_{:02}'.format(i),self.workdir,time = i/float(self.frames))
  File "/usr/lib/python2.7/site-packages/adage/visualize.py", line 68, in print_dag
    save_dot(colorize_graph(dag,time).to_string(),pngfilename,'png')
  File "/usr/lib/python2.7/site-packages/adage/visualize.py", line 24, in colorize_graph
    start = min([dag.getNode(n).define_time for n in allnodes])
ValueError: min() arg is an empty sequence
```

**Comment by lukasheinrich** [comment]
seems like your missing init pars? try with

```
{
"preset_pars": {"name": "Diego"}
}
```

**Comment by diegodelemos** [comment]
Solved rebuilding `reana-workflow-engine-yadage` docker image so latest `yadage-schemas` was installed:
```console
$ docker build . --no-cache -t reana-workflow-engine-yadage
```
[`yadage-schemas 5.2.0`](https://github.com/diana-hep/yadage-schemas/blob/960ed122a5790d9c2ce45b838c87591e82215a78/yadageschemas/__init__.py) didn't support generic GitHub URLs
